server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package:com.examole.pojo
  mapper-location:classpath:/mybatis/*.xml
logging:
  file:
    name: log/log.log
  level:
    root: info


